# Generated by Django 6.0.5 on 2026-08-04 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentcategory'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
