# Generated by Django 6.0.5 on 2026-08-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_merchant_business_category_and_more'),
        ('payments', '0002_remove_transaction_merchant_transaction_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.AlterUniqueTogether(
            name='businessmember',
            unique_together={('business', 'user')},
        ),
    ]
