# Generated by Django 6.0.5 on 2026-08-09 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('key', 'endpoint')},
            },
        ),
    ]
