# Generated by Django 6.0.5 on 2026-08-04 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name_sw', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('is_mandatory_electronic', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('COLLECTION', 'Collection (In)'), ('PAYOUT', 'Payout (Out)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('channel', models.CharField(choices=[('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTEL', 'Airtel Money'), ('HALOPESA', 'Halo Pesa'), ('CARD', 'Card'), ('BANK', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('selcom_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('selcom_transid', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500, null=True)),
                ('payer_msisdn', models.CharField(blank=True, max_length=15, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentcategory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.merchant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
