# Generated by Django 6.0.5 on 2026-08-04 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('SELCOM', 'Selcom')], default='SELCOM', max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
